// Import the `createSlice` function from the "@reduxjs/toolkit" library.
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the products slice of the Redux store.
export const initialState = {
  loading: false, // Represents whether data is being fetched
  error: null, // Stores error information if any
  products: [], // Stores the list of products
};

// Create a products slice using `createSlice`.
export const productsSlice = createSlice({
  name: "products", // The name of the slice, used to generate action types
  initialState, // Initial state defined earlier
  reducers: {
    // Define Redux actions (reducers) to modify the state.

    // Sets the `loading` state to `true`.
    setLoading: (state) => {
      state.loading = true;
    },

    // Updates `loading` to `false`, clears any previous errors, and sets the `products` list.
    setProducts: (state, { payload }) => {
      state.loading = false;
      state.error = null;
      state.products = payload;
    },

    // Sets the `error` state and sets `loading` to `false`.
    setError: (state, { payload }) => {
      state.error = payload;
      state.loading = false;
    },
  },
});

// Export the action creators (functions that generate actions) as named exports.
export const { setLoading, setError, setProducts } = productsSlice.actions;

// Export the reducer function generated by `createSlice` as the default export.
export default productsSlice.reducer;

// Selector function to access the products state from the Redux store.
export const productSelector = (state) => state.products;
